// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAfTJcq5XY8r2pw40W5odP4dcVC52uISNs',
    appId: '1:940847910389:web:aacdf2fb7e046695fce4bc',
    messagingSenderId: '940847910389',
    projectId: 'traiffguad-ai',
    authDomain: 'traiffguad-ai.firebaseapp.com',
    storageBucket: 'traiffguad-ai.firebasestorage.app',
    measurementId: 'G-YTYWDJMM7L',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAzc63xu-98UOX6vsaACUFgFzstpFRevCI',
    appId: '1:940847910389:android:3ded9c9f972753e7fce4bc',
    messagingSenderId: '940847910389',
    projectId: 'traiffguad-ai',
    storageBucket: 'traiffguad-ai.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB9oalsM9k0kTkgbf-SP7Bg7keo17hE9sI',
    appId: '1:940847910389:ios:9904dad503591bf1fce4bc',
    messagingSenderId: '940847910389',
    projectId: 'traiffguad-ai',
    storageBucket: 'traiffguad-ai.firebasestorage.app',
    iosBundleId: 'com.example.hscodeAuditor',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB9oalsM9k0kTkgbf-SP7Bg7keo17hE9sI',
    appId: '1:940847910389:ios:9904dad503591bf1fce4bc',
    messagingSenderId: '940847910389',
    projectId: 'traiffguad-ai',
    storageBucket: 'traiffguad-ai.firebasestorage.app',
    iosBundleId: 'com.example.hscodeAuditor',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAfTJcq5XY8r2pw40W5odP4dcVC52uISNs',
    appId: '1:940847910389:web:df028ad2b1d75b82fce4bc',
    messagingSenderId: '940847910389',
    projectId: 'traiffguad-ai',
    authDomain: 'traiffguad-ai.firebaseapp.com',
    storageBucket: 'traiffguad-ai.firebasestorage.app',
    measurementId: 'G-FRYMQ9408F',
  );
}
